# .gitpod.yml
image:
  file: .devcontainer/Dockerfile.dev

tasks:
  - name: Install project deps
    command: poetry install --with dev

vscode:
  extensions:
    - charliermarsh.ruff
    - github.copilot
    - GitHub.copilot-chat
    - exiasr.hadolint
    - tamasfe.even-better-toml
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.mypy-type-checker
    - github.vscode-github-actions
    - pkief.material-icon-theme

# Optional settings (if not covered in devcontainer.json)
github:
  prebuilds:
    enabled: true
