"""Initial schema

Revision ID: c89f32aa181f
Revises: 
Create Date: 2025-05-18 18:43:42.578744

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c89f32aa181f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
